<program> ::= <statement-list>

<statement-list> ::= <statement>*

<statement> ::= "let" <identifier> "=" <expr> ";"
         | <identifier> "=" <expr> ";"
         | "loop" <expr> <block> ";"
         | "print" <expr> ";"

<block> ::= "{" <statement-list> "}"

<expr> ::= <term>
         | <term> "+" <expr>

<term> ::= <identifier>
         | <number>

<identifier> ::= /[A-Za-z][A-Za-z0-9]*/

<number>     ::= /[0-9]+/
